name: Deploy Pre-built Files to S3

on:
  push:
    branches:
      - main
    paths:
      - 'out/**'  # out 디렉토리의 변경사항만 감지

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Deploy HTML files to S3 (no cache)
        run: |
          aws s3 sync ./out/ s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.html" \
            --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html; charset=utf-8"
          
      - name: Deploy static assets to S3 (with cache)
        run: |
          aws s3 sync ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete --exclude "*.html" --cache-control "public,max-age=31536000"
      
      - name: Update S3 website configuration
        run: |
          aws s3 website s3://${{ secrets.AWS_S3_BUCKET }} --index-document index.html --error-document index.html 