name: Deploy to AWS S3 (Full Build)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'out/**'  # out 폴더 변경 사항은 무시 (다른 워크플로우에서 처리)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 서울 리전, 필요시 변경
          
      - name: Update S3 website configuration
        run: |
          aws s3 website s3://${{ secrets.AWS_S3_BUCKET }} --index-document index.html --error-document index.html
          
      - name: Deploy HTML files to S3 (no cache)
        run: |
          aws s3 sync ./out/ s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.html" \
            --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html; charset=utf-8"
          
      - name: Deploy static assets to S3 (with cache)
        run: |
          aws s3 sync ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete --exclude "*.html" --cache-control "public,max-age=31536000"
      
      - name: Invalidate CloudFront (if using CDN)
        if: ${{ env.CLOUDFRONT_DISTRIBUTION_ID != '' }}
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
          fi 