name: Deploy to S3

on:
  push:
    branches:
      - main

# GitHub Actions 권한 설정
permissions:
  contents: read  # S3에 배포만 하므로 읽기 권한만 필요

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      # S3 웹사이트 설정 업데이트
      - name: Update S3 website configuration
        run: |
          aws s3 website s3://${{ secrets.AWS_S3_BUCKET }} --index-document index.html --error-document 404.html
          
      # out 폴더의 모든 콘텐츠를 있는 그대로 S3에 동기화
      - name: Deploy entire out folder to S3
        run: |
          aws s3 sync ./out/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
      
      # CloudFront 캐시 무효화 (CDN 사용 시)
      - name: Invalidate CloudFront (if using CDN)
        if: ${{ env.CLOUDFRONT_DISTRIBUTION_ID != '' }}
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
          fi 